### ISSUE TITLE
Issue with on-screen keyboard on Sign-Up Page

### ISSUE THREAD

**Issue by adrian-szwejk** [SiGMobileUIUC/car_pool_app#3]
Only for the sign-up page when I try to use the on-screen keyboard to type in my email/password it stops working after 1 character and throws errors in the Debug Console saying "getTextBeforeCursor on inactive Connection" as well as a bunch other errors that spam/fill the debug console and bug the screen out. Only typing on laptop keyboard works within emulator. Issue doesn't persist within Login so try seeing what different between two screens textFields

**Comment by adrian-szwejk** [comment]
Fixed issue by simply removing the changes made to controllers within the initState method in SignUpPage however not sure if I remove some functionality so please lmk what was the plan with that code

**Comment by ashah305** [comment]
Okay, I have been testing on my laptop so I did not have that issue. For now, leave your changes in, and I will get back to that part eventually.

**Comment by vicnvx** [comment]
> Fixed issue by simply removing the changes made to controllers within the initState method in SignUpPage however not sure if I remove some functionality so please lmk what was the plan with that code


Hey yeah we don't need any of that code in initState on the sign up form.
I think i was following a tutorial somewhere and I thought that part was needed.
