### ISSUE TITLE
Invalid AssetImage when loading Account Page

### ISSUE THREAD

**Issue by adrian-szwejk** [SiGMobileUIUC/car_pool_app#4]
When I tried going to the Account screen I got imageProvider error which is usually when trying to access invalid directory assets which appears to be on Line: 48 of "account.dart" where there's a reference to an asset folder but when I pulled repo it didn't have one in directory so either add that or remove this line.

**Comment by ashah305** [comment]
What line are you referring to? I think I moved around some code before I saw this so it may be different now. Sorry!

**Comment by adrian-szwejk** [comment]
Actually I'm not sure anymore, but it was an asset image that was pull from the assets folder of the repo but it looks like it may have been fixed to pick and image from the users camera roll instead so I guess the issue has been resolved.
