### ISSUE TITLE
Use Listview.Builder with ListTiles instead of HardCoding in Account.Dart

### ISSUE THREAD

**Issue by adrian-szwejk** [SiGMobileUIUC/car_pool_app#5]
Hey, so for listTiles created within account page I noticed their hard coded in each of them even though they all have a very similar format and input. So, in order to help save space in this already really long file I recommend checking out Listview.builder and use the ListTiles as the children: https://www.geeksforgeeks.org/listview-builder-in-flutter/.
![image](https://github.com/SiGMobileUIUC/car_pool_app/assets/77693969/52abd7b7-21fb-4710-9f89-a5bca730c673)

**Comment by ashah305** [comment]
Will take a look this week, thanks!

**Comment by ashah305** [comment]
I completed this. Adrian just look it over when  you get the chance, and if it is good then go ahead and close it. If not, lmk what to fix.

**Comment by adrian-szwejk** [comment]
Yeah, it looks like there was some sizing issue with using the listview.builder inside of a singleChildScrollView so I switched it over to a Sliver system with Sliver list and SliverToBoxAdapter for the pfp. There seems to still be some unnecessary code within the SliverList/Listview.builder now as you just moved the switch case inside of it rather than creating a list and using the index to grab information without cases.

**Comment by adrian-szwejk** [comment]
Finished sliverlist.builder and connection with parameterized function 
commit 8f97a20
